[package]
name = "polars_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.46", features = ["lazy"] }
rand = { version = "0.8.5", features = ["std_rng"] }
sysinfo = "0.29.10"